#!/bin/sh

REPO="badigit/MagiTrickle_mod_badigit"
API="https://api.github.com/repos/$REPO/releases/latest"

# Определяем архитектуру OpenWrt
ARCH=$(opkg print-architecture | awk '$2 == "priority" && $3 == "10" {print $1}')

echo "Detected architecture: $ARCH"

# Получаем один подходящий .ipk
URL=$(wget -qO- "$API" | \
grep browser_download_url | \
grep "$ARCH" | \
grep "openwrt" | \
grep ".ipk" | \
head -n1 | cut -d '"' -f 4)

if [ -z "$URL" ]; then
    echo "No matching package found for architecture: $ARCH"
    exit 1
fi

echo "Downloading: $URL"
wget -O /tmp/magitrickle.ipk "$URL"

echo "Installing..."
opkg install /tmp/magitrickle.ipk
